version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    networks:
      - duolingo-net
    depends_on:
      - mysql
    container_name: duolingo-app
    hostname: duolingo-app
    ports:
      - 8080:8080
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: db
    networks:
      - duolingo-net
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=streak_go_db
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

networks:
  duolingo-net:
